//! Shared integration-test harness.
//!
//! Provides a `TestApp` that builds the full Axum router on top of a real
//! Postgres test database, runs the migrations, and lets tests drive the HTTP
//! API with `tower::ServiceExt::oneshot` (no live listener needed).
//!
//! ## Requirements
//!
//! Tests need a running Postgres and a dedicated test database. Set
//! `ANJUMAN_TEST_DATABASE_URL` to point at it, or the harness falls back to
//! `postgres://127.0.0.1:5432/anjuman_test`. Start Postgres via
//! `nix run .#anjuman` as usual.
//!
//! ## Isolation
//!
//! `cargo test` runs test functions in parallel, but they all share one test
//! database. To keep each test deterministic the harness serializes *setup*
//! behind a global mutex and truncates the tables a test is expected to mutate
//! (resetting identity sequences) before handing back a `TestApp`. Tests must
//! therefore avoid asserting on cross-test data; each test seeds its own rows.

use std::sync::{LazyLock, Mutex};

use anjuman_server::app::app;
use anjuman_server::auth::create_token;
use anjuman_server::db_types::DbUserRole;
use anjuman_server::state::AppState;

use sqlx::PgPool;
use sqlx::postgres::PgPoolOptions;

pub use anjuman_contracts::UserRole;

/// Serializes `TestApp::new()` so parallel tests don't race each other's
/// truncate-then-insert sequences against the shared database.
static SETUP_LOCK: LazyLock<Mutex<()>> = LazyLock::new(|| Mutex::new(()));

/// Serializes DB-mutating *test bodies* (seed → act) against the shared
/// database. Unlike `SETUP_LOCK`, this is async-safe (a `tokio` mutex), so a
/// test can hold it across `.await`. Tests that insert more than one row
/// dependency (e.g. a card + its note) must hold this for their whole body, or
/// another test's `TestApp::new()` truncate can delete a half-seeded row.
static TEST_DB_LOCK: LazyLock<tokio::sync::Mutex<()>> =
    LazyLock::new(|| tokio::sync::Mutex::new(()));

/// Acquire the shared-DB test guard. Call once at the top of any `#[tokio::test]`
/// that needs deterministic DB state across multiple sequential inserts.
pub async fn db_guard() -> tokio::sync::MutexGuard<'static, ()> {
    TEST_DB_LOCK.lock().await
}

/// A fully-built router + its database pool.
///
/// `Clone` leans on `Router`/`PgPool` both being cheaply cloneable, so a single
/// `TestApp` can back many `oneshot` requests within one `#[tokio::test]`.
#[derive(Clone)]
pub struct TestApp {
    pub app: axum::Router,
    pub db: PgPool,
}

impl TestApp {
    /// Connect to the test database, migrate, truncate mutable tables, and
    /// return a ready-to-use application.
    pub async fn new() -> Self {
        let url = std::env::var("ANJUMAN_TEST_DATABASE_URL")
            .unwrap_or_else(|_| "postgres://127.0.0.1:5432/anjuman_test".to_string());

        // Serialize DB setup across parallel tests.
        let _guard = SETUP_LOCK.lock().unwrap_or_else(|e| e.into_inner());

        let db = PgPoolOptions::new()
            .max_connections(5)
            .connect(&url)
            .await
            .expect("connect to test database");

        // `cargo test` runs both `0001` (schema) and `0002` (seed). The seed is
        // idempotent and provides the id-0 global-default deck-options preset
        // that request handling expects.
        sqlx::migrate!("./migrations")
            .run(&db)
            .await
            .expect("run migrations");

        // Reset the tables tests mutate, and their identity sequences, so each
        // test starts from a predictable, empty state (except the id-0 preset).
        reset_mutable_tables(&db).await;

        let state = AppState { db: db.clone() };

        TestApp {
            app: app(state),
            db,
        }
    }

    /// Issue a JWT for `user_id` with the given role, for authenticated tests.
    pub fn token(&self, user_id: i64, role: UserRole) -> String {
        create_token(user_id, 1, role).expect("create test token")
    }
}

/// Truncate tables that tests insert into, and restart their identity sequences.
async fn reset_mutable_tables(db: &PgPool) {
    // Order matters for FK constraints: children before parents.
    sqlx::query(
        r#"
        TRUNCATE TABLE
            reviews,
            student_card_states,
            cards,
            notes,
            deck_classes,
            deck_collaborators,
            class_members,
            classes,
            decks,
            note_type_templates,
            note_types,
            user_preferences,
            revoked_tokens,
            users
        RESTART IDENTITY CASCADE
        "#,
    )
    .execute(db)
    .await
    .expect("truncate mutable tables");

    // The `users` table seeded via `GENERATED BY DEFAULT AS IDENTITY` needs its
    // sequence advanced past the id-0 school/preset identities we keep.
    sqlx::query("SELECT setval(pg_get_serial_sequence('users','id'), 1, false)")
        .execute(db)
        .await
        .expect("reset users sequence");
}

/// Create a user and return its id + a bearer token for it.
///
/// `school_id` is always 1 (the dev school the seed data provides).
pub async fn create_user(app: &TestApp, role: UserRole) -> (i64, String) {
    let inserted = sqlx::query!(
        r#"
        INSERT INTO users (school_id, email, password_hash, role, first_name, last_name)
        VALUES (1, $1, 'x', $2::text::user_role, 'Test', 'User')
        RETURNING id
        "#,
        // unique email per test user
        uuid::Uuid::new_v4().to_string() + "@test.local",
        DbUserRole::from(role).as_str(),
    )
    .fetch_one(&app.db)
    .await
    .expect("insert test user");

    (inserted.id, app.token(inserted.id, role))
}

/// Seed a minimal studiable card (deck + note type + template + note + card +
/// student state) and return `(student_id, card_id)`. The card starts in
/// `state` with the given `step_index`.
pub async fn seed_studiable_card(
    app: &TestApp,
    student_id: i64,
    state: &str,
    step_index: i64,
) -> i64 {
    let deck_id = sqlx::query!(
        "INSERT INTO decks (school_id, title, created_by) VALUES (1, 'Test Deck', $1) RETURNING id",
        student_id
    )
    .fetch_one(&app.db)
    .await
    .expect("insert deck")
    .id;

    let note_type_id = sqlx::query!(
        "INSERT INTO note_types (school_id, name, field_names) VALUES (1, 'Basic', '[\"Front\",\"Back\"]') RETURNING id"
    )
    .fetch_one(&app.db)
    .await
    .expect("insert note type")
    .id;

    let template_id = sqlx::query!(
        "INSERT INTO note_type_templates (note_type_id, ord, name, front_pattern, back_pattern) VALUES ($1, 0, 'Card 1', '{{Front}}', '{{Front}}<hr>{{Back}}') RETURNING id",
        note_type_id
    )
    .fetch_one(&app.db)
    .await
    .expect("insert template")
    .id;

    let note_id = sqlx::query!(
        "INSERT INTO notes (note_type_id, fields_json) VALUES ($1, '{\"Front\":\"Q\",\"Back\":\"A\"}') RETURNING id",
        note_type_id
    )
    .fetch_one(&app.db)
    .await
    .expect("insert note")
    .id;

    let card_id = sqlx::query!(
        "INSERT INTO cards (note_id, deck_id, template_id) VALUES ($1, $2, $3) RETURNING id",
        note_id,
        deck_id,
        template_id
    )
    .fetch_one(&app.db)
    .await
    .expect("insert card")
    .id;

    sqlx::query!(
        "INSERT INTO student_card_states (student_id, card_id, state, stability, difficulty, reps, lapses, step_index) VALUES ($1, $2, $3::text::card_state, 0.0, 0.0, 0, 0, $4)",
        student_id,
        card_id,
        state,
        step_index
    )
    .execute(&app.db)
    .await
    .expect("insert student card state");

    card_id
}
