-- Anjuman consolidated schema (Postgres).
--
-- Single source of truth for the dev schema. Replaces the ~34 incremental
-- SQLite migrations; there is no production data to preserve.

--------------------------------------------------------------------
-- Enum types
--------------------------------------------------------------------

CREATE TYPE user_role AS ENUM ('admin', 'teacher', 'student');
CREATE TYPE membership_role AS ENUM ('teacher', 'student');
CREATE TYPE card_state AS ENUM ('new', 'learning', 'review', 'relearning');
CREATE TYPE step_kind AS ENUM ('learning', 'relearning');

--------------------------------------------------------------------
-- Schools
--------------------------------------------------------------------

CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

--------------------------------------------------------------------
-- Users
--------------------------------------------------------------------

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,

    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,

    role user_role NOT NULL,

    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (school_id)
        REFERENCES schools(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_users_school ON users(school_id);

--------------------------------------------------------------------
-- Classes
--------------------------------------------------------------------

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,

    name TEXT NOT NULL,
    description TEXT,

    archived BOOLEAN NOT NULL DEFAULT FALSE,

    created_by BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (school_id)
        REFERENCES schools(id)
        ON DELETE CASCADE,

    FOREIGN KEY (created_by)
        REFERENCES users(id)
);

CREATE INDEX idx_classes_school ON classes(school_id);

--------------------------------------------------------------------
-- Class membership
--------------------------------------------------------------------

CREATE TABLE class_members (
    class_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    role membership_role NOT NULL,

    joined_at TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (class_id, user_id),

    FOREIGN KEY (class_id)
        REFERENCES classes(id)
        ON DELETE CASCADE,

    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_class_members_user ON class_members(user_id);

--------------------------------------------------------------------
-- Deck options (scheduling presets)
--------------------------------------------------------------------

CREATE TABLE deck_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name TEXT NOT NULL,

    desired_retention DOUBLE PRECISION NOT NULL DEFAULT 0.9,
    bury_new BOOLEAN NOT NULL DEFAULT FALSE,
    bury_review BOOLEAN NOT NULL DEFAULT FALSE,
    bury_interday BOOLEAN NOT NULL DEFAULT FALSE,
    new_per_day BIGINT NOT NULL DEFAULT 20,
    review_per_day BIGINT NOT NULL DEFAULT 200,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
    UNIQUE (school_id, name)
);

CREATE TABLE deck_option_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    options_id BIGINT NOT NULL,
    kind step_kind NOT NULL,
    step_index BIGINT NOT NULL,
    seconds BIGINT NOT NULL,

    FOREIGN KEY (options_id) REFERENCES deck_options(id) ON DELETE CASCADE,
    UNIQUE (options_id, kind, step_index)
);

CREATE INDEX idx_deck_option_steps_options
    ON deck_option_steps(options_id, kind, step_index);

--------------------------------------------------------------------
-- Decks
--------------------------------------------------------------------

CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    school_id BIGINT NOT NULL,

    title TEXT NOT NULL,
    description TEXT,

    created_by BIGINT NOT NULL,

    parent_id BIGINT,
    options_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (school_id)
        REFERENCES schools(id)
        ON DELETE CASCADE,

    FOREIGN KEY (created_by)
        REFERENCES users(id),

    FOREIGN KEY (parent_id)
        REFERENCES decks(id)
        ON DELETE CASCADE,

    FOREIGN KEY (options_id)
        REFERENCES deck_options(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_decks_school ON decks(school_id);
CREATE INDEX idx_decks_parent ON decks(parent_id);

--------------------------------------------------------------------
-- Deck-to-class sharing / collaborators
--------------------------------------------------------------------

CREATE TABLE deck_classes (
    deck_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (deck_id, class_id),

    FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE INDEX idx_deck_classes_class ON deck_classes(class_id);

CREATE TABLE deck_collaborators (
    deck_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    shared_at TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (deck_id, user_id),

    FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_deck_collaborators_user ON deck_collaborators(user_id);

--------------------------------------------------------------------
-- Note types & templates
--------------------------------------------------------------------

CREATE TABLE note_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    field_names JSONB NOT NULL,
    sort_field TEXT NOT NULL DEFAULT '',
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    UNIQUE (school_id, name)
);

CREATE TABLE note_type_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_type_id BIGINT NOT NULL,
    ord BIGINT NOT NULL,
    name TEXT NOT NULL,
    front_pattern TEXT NOT NULL,
    back_pattern TEXT NOT NULL,

    FOREIGN KEY (note_type_id) REFERENCES note_types(id) ON DELETE CASCADE,
    UNIQUE (note_type_id, ord)
);

--------------------------------------------------------------------
-- Notes
--------------------------------------------------------------------

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_type_id BIGINT NOT NULL,
    fields_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (note_type_id) REFERENCES note_types(id)
);

CREATE INDEX idx_notes_note_type ON notes(note_type_id);

--------------------------------------------------------------------
-- Cards
--------------------------------------------------------------------

CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    deck_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE,
    FOREIGN KEY (template_id) REFERENCES note_type_templates(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_cards_note_template ON cards(note_id, template_id);
CREATE INDEX idx_cards_deck ON cards(deck_id);

--------------------------------------------------------------------
-- Per-student scheduling state (FSRS)
--------------------------------------------------------------------

CREATE TABLE student_card_states (
    student_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,

    state card_state NOT NULL,

    stability DOUBLE PRECISION NOT NULL,
    difficulty DOUBLE PRECISION NOT NULL,

    due_at TIMESTAMPTZ,
    last_reviewed_at TIMESTAMPTZ,

    reps BIGINT NOT NULL DEFAULT 0,
    lapses BIGINT NOT NULL DEFAULT 0,

    flag BIGINT NOT NULL DEFAULT 0,
    step_index BIGINT NOT NULL DEFAULT 0,
    suspended BOOLEAN NOT NULL DEFAULT FALSE,
    buried_at TIMESTAMPTZ,
    bury_reason TEXT,

    PRIMARY KEY (student_id, card_id),

    FOREIGN KEY (student_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    FOREIGN KEY (card_id)
        REFERENCES cards(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_due_cards ON student_card_states(student_id, due_at);

--------------------------------------------------------------------
-- Review history
--------------------------------------------------------------------

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,

    rating BIGINT NOT NULL CHECK (rating BETWEEN 1 AND 4),

    reviewed_at TIMESTAMPTZ NOT NULL,

    response_time_ms BIGINT,

    state_before TEXT NOT NULL DEFAULT 'review',

    FOREIGN KEY (student_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    FOREIGN KEY (card_id)
        REFERENCES cards(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_reviews_student ON reviews(student_id);
CREATE INDEX idx_reviews_card ON reviews(card_id);
CREATE INDEX idx_reviews_time ON reviews(reviewed_at);

--------------------------------------------------------------------
-- Per-user scheduling preferences
--------------------------------------------------------------------

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    learn_ahead_seconds BIGINT NOT NULL DEFAULT 1200,
    day_start_hour BIGINT NOT NULL DEFAULT 4,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

--------------------------------------------------------------------
-- Revoked tokens (JWT logout blocklist)
--------------------------------------------------------------------

CREATE TABLE revoked_tokens (
    jti TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_revoked_tokens_expires ON revoked_tokens(expires_at);
